### ISSUE TITLE
Lossy (transcoded JPEG) JXL fails to decode

### ISSUE THREAD

**Issue by alistair7** [libjxl/jxl-rs#437]
The attached file fails to decode (renamed to .jpg for github).

jxl_cli 20220917_121258.jxl out.png

![Image](https://github.com/user-attachments/assets/7cbfbbc3-5fcf-4958-a185-c1a4a94e4ccb)

<details>
<summary>Backtrace</summary>

```
thread 'main' panicked at jxl_cli/src/main.rs:223:18:
called `Result::unwrap()` on an `Err` value: TreeTooLarge(1025, 1024)
stack backtrace:
   0:     0x55e8de1af932 - <std::sys::backtrace::BacktraceLock::print::DisplayBacktrace as core::fmt::Display>::fmt::h2cc8991c1989188c
   1:     0x55e8de1d29ef - core::fmt::write::h46aa79f218fb371f
   2:     0x55e8de1ace83 - std::io::Write::write_fmt::hc90fa0bff996c16c
   3:     0x55e8de1af782 - std::sys::backtrace::BacktraceLock::print::h8a32f8583be7dea8
   4:     0x55e8de1b0954 - std::panicking::default_hook::{{closure}}::hd56ccaf051030dc8
   5:     0x55e8de1b0775 - std::panicking::default_hook::h1d9a87fc8bf976b2
   6:     0x55e8de1b1365 - std::panicking::rust_panic_with_hook::hbbf532f4481fe8ec
   7:     0x55e8de1b10fa - std::panicking::begin_panic_handler::{{closure}}::hd75205fc21d185eb
   8:     0x55e8de1afe29 - std::sys::backtrace::__rust_end_short_backtrace::h51d265006343ab8e
   9:     0x55e8de1b0d8d - __rustc[4f3f6d6dc60a4a1e]::rust_begin_unwind
  10:     0x55e8de1d05c0 - core::panicking::panic_fmt::h57a3e618eea51d64
  11:     0x55e8de1d0a26 - core::result::unwrap_failed::h8f6d047f1c4ea6f5
  12:     0x55e8dd7cc4e0 - core::result::Result<T,E>::unwrap::h466b7c1bf6a5cc98
                               at /usr/src/debug/rust/rustc-1.90.0-src/library/core/src/result.rs:1167:23
  13:     0x55e8dd7cc4e0 - jxl_cli::main::h486f6484ad35593d
                               at /home/user/build/jxl-rs/jxl_cli/src/main.rs:223:18
  14:     0x55e8dd80e16b - core::ops::function::FnOnce::call_once::h74e6314a6dabb734
                               at /usr/src/debug/rust/rustc-1.90.0-src/library/core/src/ops/function.rs:253:5
  15:     0x55e8dd80c5cd - std::sys::backtrace::__rust_begin_short_backtrace::h7f46b22827cb8e15
                               at /usr/src/debug/rust/rustc-1.90.0-src/library/std/src/sys/backtrace.rs:158:18
  16:     0x55e8dd7e9ac1 - std::rt::lang_start::{{closure}}::h1c699afbcaccf50f
                               at /usr/src/debug/rust/rustc-1.90.0-src/library/std/src/rt.rs:206:18
  17:     0x55e8de1a5850 - std::rt::lang_start_internal::h4b008718081a8f88
  18:     0x55e8dd7e9aa7 - std::rt::lang_start::hdf03d7d694423327
                               at /usr/src/debug/rust/rustc-1.90.0-src/library/std/src/rt.rs:205:5
  19:     0x55e8dd7cefae - main
  20:     0x7ffab0a27675 - <unknown>
  21:     0x7ffab0a27729 - __libc_start_main
  22:     0x55e8dd7c5b15 - _start
  23:                0x0 - <unknown>


```

</details>

**Comment by veluca93** [comment]
I think this was fixed by #439, can you check?

**Comment by alistair7** [comment]
Still fails on this one.  (I am able to decode the example from #428.)

**Comment by veluca93** [comment]
That's surprising... @tirr-c would you be able to check what's going on here since you fixed a similar failure?
